import { MenuItem, NavLink, Testimonial } from './types';
import { ChefHat, Leaf, Star, Flame } from 'lucide-react';

export const NAV_LINKS: NavLink[] = [
  // Home link removed as per request (Logo serves as Home)
  { label: 'Menu', path: '/menu' },
  { label: 'Trays', path: '/party-trays' },
  { label: 'Catering', path: '/catering' },
  { label: 'Gallery', path: '/gallery' },
  { label: 'About', path: '/about' },
  { label: 'Contact', path: '/contact' },
];

export const MENU_CATEGORIES = [
  'All',
  'Appetizers',
  'Tandoor',
  'Chicken',
  'Lamb & Goat',
  'Seafood',
  'Vegetarian',
  'Biryani',
  'Breads',
  'Desserts',
  'Beverages'
];

export const MENU_ITEMS: MenuItem[] = [
  // --- Vegetarian Appetizers ---
  {
    id: 'a1',
    name: 'Vegetable Samosa (2 pcs)',
    description: 'Crispy pastry turnover filled with seasoned potatoes and green peas.',
    price: '$6',
    category: 'Appetizers',
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'a2',
    name: 'Samosa Chaat',
    description: 'Samosas topped with chickpeas, yogurt, mint, and tamarind chutneys.',
    price: '$9',
    category: 'Appetizers',
    isVegetarian: true,
  },
  {
    id: 'a3',
    name: 'Aloo Tikki Chaat',
    description: 'Potato patties topped with seasoned chickpeas, yogurt, and chutneys.',
    price: '$9',
    category: 'Appetizers',
    isVegetarian: true,
  },
  {
    id: 'a4',
    name: 'Lasooni Gobi',
    description: 'Crispy cauliflower florets tossed in a tangy garlic tomato sauce.',
    price: '$10',
    category: 'Appetizers',
    isVegetarian: true,
    isVegan: true,
    isChefSpecial: true,
  },
  {
    id: 'a5',
    name: 'Gobi Manchurian',
    description: 'Cauliflower florets tossed in a spicy soy-garlic Indo-Chinese sauce.',
    price: '$10',
    category: 'Appetizers',
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'a6',
    name: 'Chilli Paneer',
    description: 'Cubes of cottage cheese sautéed with onions, bell peppers, and green chillies.',
    price: '$12',
    category: 'Appetizers',
    isVegetarian: true,
  },
  {
    id: 'a7',
    name: 'Hara Bhara Kabab',
    description: 'Pan-seared patties made with spinach, green peas, and potatoes.',
    price: '$10',
    category: 'Appetizers',
    isVegetarian: true,
  },
  {
    id: 'a8',
    name: 'Kurkuri Bhindi',
    description: 'Crispy okra fries dusted with mango powder and chaat masala.',
    price: '$9',
    category: 'Appetizers',
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'a9',
    name: 'Mix Veg Platter',
    description: 'Assortment of Samosa, Hara Bhara Kabab, and Pakoras.',
    price: '$13',
    category: 'Appetizers',
    isVegetarian: true,
  },

  // --- Non-Veg Appetizers ---
  {
    id: 'nv1',
    name: 'Meat Samosa (2 pcs)',
    description: 'Crispy pastry filled with seasoned minced lamb and peas.',
    price: '$8',
    category: 'Appetizers',
  },
  {
    id: 'nv2',
    name: 'Chicken 65',
    description: 'Spicy, deep-fried chicken bites marinated in ginger, garlic, and red chilies.',
    price: '$12',
    category: 'Appetizers',
  },
  {
    id: 'nv3',
    name: 'Chilli Chicken',
    description: 'Crispy chicken tossed with onions, bell peppers, and spicy chilli sauce.',
    price: '$12',
    category: 'Appetizers',
  },
  {
    id: 'nv4',
    name: 'Chicken Manchurian',
    description: 'Indo-Chinese style chicken tossed in a savory soy-garlic sauce.',
    price: '$12',
    category: 'Appetizers',
  },
  {
    id: 'nv5',
    name: 'Fish Amritsari',
    description: 'Crispy battered fish fritters seasoned with carom seeds and spices.',
    price: '$13',
    category: 'Appetizers',
  },
  {
    id: 'nv6',
    name: 'Shrimp Balchao',
    description: 'Pan-seared shrimp in a fiery Goan pickle marinade.',
    price: '$14',
    category: 'Appetizers',
    isGlutenFree: true,
  },
  {
    id: 'nv7',
    name: 'Jalwa Mix Grill (Appetizer)',
    description: 'A tasting of Chicken Tikka, Malai Kabab, and Seekh Kabab.',
    price: '$15',
    category: 'Appetizers',
    isGlutenFree: true,
  },

  // --- Tandoor ---
  {
    id: 't1',
    name: 'Tandoori Chicken',
    description: 'The classic. Chicken on the bone marinated in yogurt and traditional spices.',
    price: '$15 (Half) / $25 (Full)',
    category: 'Tandoor',
    isGlutenFree: true,
  },
  {
    id: 't2',
    name: 'Chicken Tikka',
    description: 'Boneless chicken breast cubes marinated in yogurt, lemon, and spices.',
    price: '$17',
    category: 'Tandoor',
    isGlutenFree: true,
  },
  {
    id: 't3',
    name: 'Malai Kabab',
    description: 'Chicken breast marinated in cream cheese, ginger, garlic, and cilantro.',
    price: '$17',
    category: 'Tandoor',
    isGlutenFree: true,
  },
  {
    id: 't4',
    name: 'Seekh Kabab',
    description: 'Minced lamb skewered with onions, herbs, and spices, cooked in the clay oven.',
    price: '$19',
    category: 'Tandoor',
    isGlutenFree: true,
  },
  {
    id: 't5',
    name: 'Tandoori Lamb Chops',
    description: 'Succulent lamb chops marinated in nutmeg, cinnamon, and aromatic herbs.',
    price: '$26',
    category: 'Tandoor',
    isGlutenFree: true,
    isChefSpecial: true,
  },
  {
    id: 't6',
    name: 'Tandoori Shrimp',
    description: 'Jumbo shrimp marinated in ajwain (carom seeds), yogurt, and spices.',
    price: '$22',
    category: 'Tandoor',
    isGlutenFree: true,
  },
  {
    id: 't7',
    name: 'Salmon Tikka',
    description: 'Fresh salmon cubes marinated in yogurt and spices, grilled to perfection.',
    price: '$23',
    category: 'Tandoor',
    isGlutenFree: true,
  },
  {
    id: 't8',
    name: 'Paneer Tikka',
    description: 'Cottage cheese cubes marinated in yogurt and spices, grilled with peppers and onions.',
    price: '$16',
    category: 'Tandoor',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 't9',
    name: 'Jalwa Mixed Grill',
    description: 'A platter of Tandoori Chicken, Chicken Tikka, Malai Kabab, Seekh Kabab, and Shrimp.',
    price: '$28',
    category: 'Tandoor',
    isGlutenFree: true,
    isChefSpecial: true,
  },

  // --- Chicken Entrées ---
  {
    id: 'c1',
    name: 'Butter Chicken (Makhani)',
    description: 'Tandoor-cooked chicken simmered in a rich, creamy tomato fenugreek sauce.',
    price: '$18',
    category: 'Chicken',
    isGlutenFree: true,
  },
  {
    id: 'c2',
    name: 'Chicken Tikka Masala',
    description: 'Chicken tikka cooked in a creamy tomato and onion sauce with bell peppers.',
    price: '$18',
    category: 'Chicken',
    isGlutenFree: true,
  },
  {
    id: 'c3',
    name: 'Chicken Curry',
    description: 'Homestyle chicken curry cooked with onions, tomatoes, and freshly ground spices.',
    price: '$17',
    category: 'Chicken',
    isGlutenFree: true,
  },
  {
    id: 'c4',
    name: 'Chicken Korma',
    description: 'Chicken cooked in a mild, creamy almond and cashew nut sauce.',
    price: '$18',
    category: 'Chicken',
    isGlutenFree: true,
  },
  {
    id: 'c5',
    name: 'Chicken Vindaloo',
    description: 'A fiery Goan dish with chicken and potatoes in a spicy vinegar-based sauce.',
    price: '$17',
    category: 'Chicken',
    isGlutenFree: true,
  },
  {
    id: 'c6',
    name: 'Chicken Saag',
    description: 'Tender chicken pieces cooked with fresh spinach and mild spices.',
    price: '$18',
    category: 'Chicken',
    isGlutenFree: true,
  },
  {
    id: 'c7',
    name: 'Chicken Chettinad',
    description: 'South Indian specialty with coconut, curry leaves, and black pepper.',
    price: '$18',
    category: 'Chicken',
    isGlutenFree: true,
  },
  {
    id: 'c8',
    name: 'Chicken Lababdar',
    description: 'Boneless chicken cooked in a rich onion and tomato sauce with a touch of cream.',
    price: '$18',
    category: 'Chicken',
    isGlutenFree: true,
  },
  {
    id: 'c9',
    name: 'Chicken Kadai',
    description: 'Chicken cooked with bell peppers, onions, tomatoes, and freshly ground spices.',
    price: '$18',
    category: 'Chicken',
    isGlutenFree: true,
  },

  // --- Lamb & Goat Entrées ---
  {
    id: 'l1',
    name: 'Lamb Rogan Josh',
    description: 'Kashmiri delicacy. Lamb cooked in an aromatic gravy with fennel and dry ginger.',
    price: '$21',
    category: 'Lamb & Goat',
    isGlutenFree: true,
  },
  {
    id: 'l2',
    name: 'Lamb Vindaloo',
    description: 'Tender lamb and potatoes cooked in a spicy red chili and vinegar sauce.',
    price: '$21',
    category: 'Lamb & Goat',
    isGlutenFree: true,
  },
  {
    id: 'l3',
    name: 'Lamb Korma',
    description: 'Lamb cooked in a rich, creamy cashew and almond sauce.',
    price: '$22',
    category: 'Lamb & Goat',
    isGlutenFree: true,
  },
  {
    id: 'l4',
    name: 'Lamb Saag',
    description: 'Tender lamb cubes cooked with fresh spinach and mild spices.',
    price: '$22',
    category: 'Lamb & Goat',
    isGlutenFree: true,
  },
  {
    id: 'l5',
    name: 'Goat Curry',
    description: 'Bone-in goat meat slow-cooked with traditional spices.',
    price: '$22',
    category: 'Lamb & Goat',
    isGlutenFree: true,
    isChefSpecial: true,
  },
  {
    id: 'l6',
    name: 'Goat Bhuna',
    description: 'Bone-in goat stir-fried with onions, bell peppers, and tomatoes.',
    price: '$22',
    category: 'Lamb & Goat',
    isGlutenFree: true,
  },

  // --- Seafood Entrées ---
  {
    id: 's1',
    name: 'Goan Fish Curry',
    description: 'Fresh catch of the day simmered in a coconut milk and tamarind based gravy.',
    price: '$22',
    category: 'Seafood',
    isGlutenFree: true,
  },
  {
    id: 's2',
    name: 'Shrimp Masala',
    description: 'Jumbo shrimp cooked in a spiced tomato and onion gravy.',
    price: '$23',
    category: 'Seafood',
    isGlutenFree: true,
  },
  {
    id: 's3',
    name: 'Shrimp Vindaloo',
    description: 'Shrimp and potatoes cooked in a hot and tangy chili-vinegar sauce.',
    price: '$23',
    category: 'Seafood',
    isGlutenFree: true,
  },
  {
    id: 's4',
    name: 'Fish Moilee',
    description: 'Fish fillet stewed in mild coconut milk with curry leaves and turmeric.',
    price: '$22',
    category: 'Seafood',
    isGlutenFree: true,
  },
  {
    id: 's5',
    name: 'Shrimp Saag',
    description: 'Shrimp cooked with fresh spinach and aromatic spices.',
    price: '$23',
    category: 'Seafood',
    isGlutenFree: true,
  },

  // --- Vegetarian Entrées ---
  {
    id: 'v1',
    name: 'Dal Makhani',
    description: 'Black lentils slow-cooked overnight with butter, cream, and tomato.',
    price: '$15',
    category: 'Vegetarian',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'v2',
    name: 'Yellow Dal Tadka',
    description: 'Yellow lentils tempered with cumin, garlic, onions, and tomatoes.',
    price: '$14',
    category: 'Vegetarian',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'v3',
    name: 'Paneer Tikka Masala',
    description: 'Tandoor-grilled cottage cheese in a creamy tomato sauce.',
    price: '$17',
    category: 'Vegetarian',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'v4',
    name: 'Saag Paneer',
    description: 'Cottage cheese cubes simmered in creamy spiced spinach.',
    price: '$17',
    category: 'Vegetarian',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'v5',
    name: 'Kadai Paneer',
    description: 'Cottage cheese cooked with bell peppers, onions, and freshly ground spices.',
    price: '$17',
    category: 'Vegetarian',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'v6',
    name: 'Malai Kofta',
    description: 'Vegetable and cheese dumplings in a rich cashew and cream sauce.',
    price: '$17',
    category: 'Vegetarian',
    isVegetarian: true,
  },
  {
    id: 'v7',
    name: 'Baingan Bharta',
    description: 'Smoked eggplant mashed and cooked with onions, tomatoes, and green peas.',
    price: '$16',
    category: 'Vegetarian',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'v8',
    name: 'Chana Masala',
    description: 'Chickpeas cooked in a traditional onion and tomato gravy.',
    price: '$14',
    category: 'Vegetarian',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'v9',
    name: 'Aloo Gobi',
    description: 'Cauliflower and potatoes stir-fried with ginger and cumin.',
    price: '$15',
    category: 'Vegetarian',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'v10',
    name: 'Navratan Korma',
    description: 'Mixed vegetables cooked in a mild creamy cashew sauce with fruit.',
    price: '$16',
    category: 'Vegetarian',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'v11',
    name: 'Bhindi Masala',
    description: 'Fresh okra stir-fried with onions, tomatoes, and spices.',
    price: '$15',
    category: 'Vegetarian',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'v12',
    name: 'Mutter Paneer',
    description: 'Green peas and cottage cheese cooked in a tomato-onion gravy.',
    price: '$16',
    category: 'Vegetarian',
    isVegetarian: true,
    isGlutenFree: true,
  },

  // --- Biryani & Rice ---
  {
    id: 'b1',
    name: 'Hyderabadi Chicken Biryani',
    description: 'Basmati rice cooked with marinated chicken, saffron, mint, and caramelized onions.',
    price: '$18',
    category: 'Biryani',
    isGlutenFree: true,
    isChefSpecial: true,
  },
  {
    id: 'b2',
    name: 'Lamb Biryani',
    description: 'Aromatic basmati rice cooked with tender lamb cubes and spices.',
    price: '$20',
    category: 'Biryani',
    isGlutenFree: true,
  },
  {
    id: 'b3',
    name: 'Goat Biryani',
    description: 'Bone-in goat meat layered with saffron rice and aromatic herbs.',
    price: '$21',
    category: 'Biryani',
    isGlutenFree: true,
  },
  {
    id: 'b4',
    name: 'Vegetable Biryani',
    description: 'Basmati rice cooked with garden fresh vegetables and mild spices.',
    price: '$16',
    category: 'Biryani',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'b5',
    name: 'Shrimp Biryani',
    description: 'Basmati rice cooked with spiced shrimp and herbs.',
    price: '$22',
    category: 'Biryani',
    isGlutenFree: true,
  },
  {
    id: 'b6',
    name: 'Jeera Rice',
    description: 'Basmati rice tempered with cumin seeds.',
    price: '$5',
    category: 'Biryani',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'b7',
    name: 'Lemon Rice',
    description: 'Basmati rice flavored with lemon, mustard seeds, and curry leaves.',
    price: '$6',
    category: 'Biryani',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },

  // --- Breads ---
  {
    id: 'br1',
    name: 'Naan',
    description: 'Classic leavened white bread baked in the tandoor.',
    price: '$3.50',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'br2',
    name: 'Garlic Naan',
    description: 'Naan topped with fresh chopped garlic and cilantro.',
    price: '$4.50',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'br3',
    name: 'Tandoori Roti',
    description: 'Whole wheat bread baked in the clay oven.',
    price: '$3.50',
    category: 'Breads',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'br4',
    name: 'Rosemary Olive Naan',
    description: 'A modern twist with fresh rosemary and olives.',
    price: '$5',
    category: 'Breads',
    isVegetarian: true,
    isChefSpecial: true,
  },
  {
    id: 'br5',
    name: 'Peshawari Naan',
    description: 'Sweet naan stuffed with almonds, cashews, raisins, and coconut.',
    price: '$6',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'br6',
    name: 'Cheese Naan',
    description: 'Naan stuffed with melted mozzarella cheese.',
    price: '$6',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'br7',
    name: 'Bullet Naan',
    description: 'Spicy naan topped with fresh green chilies.',
    price: '$5',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'br8',
    name: 'Onion Kulcha',
    description: 'Leavened bread stuffed with spiced onions.',
    price: '$5',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'br9',
    name: 'Bread Basket',
    description: 'Assortment of Naan, Garlic Naan, and Roti.',
    price: '$12',
    category: 'Breads',
    isVegetarian: true,
  },

  // --- Sides ---
  {
    id: 'sd1',
    name: 'Raita',
    description: 'Yogurt with cucumber and roasted cumin.',
    price: '$4',
    category: 'Breads',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'sd2',
    name: 'Mango Chutney',
    description: 'Sweet and tangy mango preserve.',
    price: '$3',
    category: 'Breads',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'sd3',
    name: 'Papadum',
    description: 'Crispy lentil wafers (2 pcs).',
    price: '$3',
    category: 'Breads',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },

  // --- Desserts ---
  {
    id: 'd1',
    name: 'Gulab Jamun',
    description: 'Deep-fried milk dumplings soaked in rose-flavored sugar syrup.',
    price: '$6',
    category: 'Desserts',
    isVegetarian: true,
  },
  {
    id: 'd2',
    name: 'Rasmalai',
    description: 'Soft cheese patties soaked in saffron-cardamom flavored milk.',
    price: '$7',
    category: 'Desserts',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'd3',
    name: 'Rice Kheer',
    description: 'Traditional rice pudding topped with nuts and raisins.',
    price: '$6',
    category: 'Desserts',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'd4',
    name: 'Gajar Halwa',
    description: 'Warm carrot pudding cooked with milk and nuts.',
    price: '$6',
    category: 'Desserts',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'd5',
    name: 'Pistachio Kulfi',
    description: 'Traditional dense Indian ice cream.',
    price: '$6',
    category: 'Desserts',
    isVegetarian: true,
    isGlutenFree: true,
  },

  // --- Beverages ---
  {
    id: 'bev1',
    name: 'Mango Lassi',
    description: 'Refreshing yogurt drink blended with sweet mango pulp.',
    price: '$5',
    category: 'Beverages',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'bev2',
    name: 'Masala Chai',
    description: 'Hot Indian tea brewed with milk and aromatic spices.',
    price: '$3.50',
    category: 'Beverages',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'bev3',
    name: 'Soft Drinks',
    description: 'Coke, Diet Coke, Sprite, Ginger Ale.',
    price: '$2.50',
    category: 'Beverages',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    text: "The food was absolutely delicious. The vibe was cozy and warm, making it the perfect place to relax and enjoy a meal with friends. I especially loved the Chat – it was bursting with flavor!",
    author: "Priyank R.",
    source: "Google Reviews"
  },
  {
    id: 't2',
    text: "Just returned from vacation, and didn't want to cook so I decided to try JALWA. I ordered over the phone on my way home from work. I was pleasantly surprised by the staff’s friendliness...",
    author: "Alice W.",
    source: "Yelp"
  },
  {
    id: 't3',
    text: "Their food and catering is constantly delicious, we have been ordering and eating in here for close to 1.5 years. Their flavors are closest to Delhi. Love their Dal Bukhara, Pandara Road...",
    author: "Rewan R.",
    source: "Google Reviews"
  }
];

export const CONTACT_INFO = {
  address: "215 Glenridge Ave, Montclair, NJ 07042",
  phone: "(973) 250-6364",
  email: "info@jalwanj.com",
  hours: [
    "Mon - Thu: 11:30 AM – 3:00 PM, 5:00 PM – 10:15 PM",
    "Fri - Sat: 11:30 AM – 3:00 PM, 5:00 PM – 10:30 PM",
    "Sun: 11:30 AM – 3:00 PM, 5:00 PM – 9:15 PM"
  ]
};

export const PARTY_TRAY_ITEMS = [
  {
    category: 'Vegetarian Appetizers',
    items: [
      { name: 'Samosa (Cocktail)', half: '$40', full: '$75' },
      { name: 'Lasooni Gobi', half: '$55', full: '$100' },
      { name: 'Hara Bhara Kabab', half: '$50', full: '$95' },
      { name: 'Paneer Tikka', half: '$60', full: '$115' },
      { name: 'Chilli Paneer', half: '$60', full: '$115' },
      { name: 'Vegetable Manchurian', half: '$55', full: '$100' },
      { name: 'Gobi Manchurian', half: '$55', full: '$100' },
    ]
  },
  {
    category: 'Non-Veg Appetizers',
    items: [
      { name: 'Chicken 65', half: '$65', full: '$125' },
      { name: 'Chicken Tikka', half: '$65', full: '$125' },
      { name: 'Chilli Chicken', half: '$65', full: '$125' },
      { name: 'Seekh Kabab (Lamb)', half: '$75', full: '$145' },
      { name: 'Fish Amritsari', half: '$70', full: '$135' },
      { name: 'Chicken Malai Kabab', half: '$65', full: '$125' },
    ]
  },
  {
    category: 'Vegetarian Curries',
    items: [
      { name: 'Dal Makhani', half: '$50', full: '$95' },
      { name: 'Paneer Tikka Masala', half: '$60', full: '$115' },
      { name: 'Saag Paneer', half: '$60', full: '$115' },
      { name: 'Malai Kofta', half: '$60', full: '$115' },
      { name: 'Chana Masala', half: '$50', full: '$95' },
      { name: 'Aloo Gobi', half: '$50', full: '$95' },
      { name: 'Mixed Vegetable Curry', half: '$50', full: '$95' },
    ]
  },
  {
    category: 'Chicken Curries',
    items: [
      { name: 'Butter Chicken', half: '$65', full: '$125' },
      { name: 'Chicken Tikka Masala', half: '$65', full: '$125' },
      { name: 'Chicken Curry (Home Style)', half: '$60', full: '$115' },
      { name: 'Chicken Korma', half: '$65', full: '$125' },
      { name: 'Chicken Vindaloo', half: '$60', full: '$115' },
      { name: 'Chicken Saag', half: '$60', full: '$115' },
      { name: 'Chicken Kadai', half: '$60', full: '$115' },
    ]
  },
  {
    category: 'Lamb & Goat',
    items: [
      { name: 'Lamb Rogan Josh', half: '$75', full: '$145' },
      { name: 'Lamb Vindaloo', half: '$75', full: '$145' },
      { name: 'Lamb Curry', half: '$75', full: '$145' },
      { name: 'Goat Curry', half: '$75', full: '$145' },
      { name: 'Goat Korma', half: '$75', full: '$145' },
    ]
  },
  {
    category: 'Seafood',
    items: [
      { name: 'Goan Fish Curry', half: '$70', full: '$135' },
      { name: 'Shrimp Masala', half: '$75', full: '$145' },
      { name: 'Shrimp Vindaloo', half: '$75', full: '$145' },
    ]
  },
  {
    category: 'Biryani & Rice',
    items: [
      { name: 'Vegetable Biryani', half: '$50', full: '$95' },
      { name: 'Chicken Biryani', half: '$60', full: '$115' },
      { name: 'Lamb Biryani', half: '$70', full: '$135' },
      { name: 'Goat Biryani', half: '$70', full: '$135' },
      { name: 'Jeera Rice', half: '$25', full: '$45' },
      { name: 'Peas Pulao', half: '$30', full: '$55' },
    ]
  },
  {
    category: 'Breads & Sides',
    items: [
      { name: 'Naan (Plain)', half: '$25', full: '$45' },
      { name: 'Naan (Garlic)', half: '$30', full: '$55' },
      { name: 'Tandoori Roti', half: '$25', full: '$45' },
      { name: 'Raita', half: '$20', full: '$35' },
      { name: 'Garden Salad', half: '$25', full: '$45' },
    ]
  },
  {
    category: 'Desserts',
    items: [
      { name: 'Gulab Jamun', half: '$40', full: '$75' },
      { name: 'Rasmalai', half: '$50', full: '$95' },
      { name: 'Rice Kheer', half: '$40', full: '$75' },
      { name: 'Gajar Halwa', half: '$45', full: '$85' },
    ]
  }
];